[tool.briefcase]
project_name = "Générateur de QCM pour AMC"
bundle = "fr.nicolas-ogier"
version = "0.0.1"
url = "https://nicolas-ogier.fr/automultiplechoicegenerator"
license = "GNU General Public License v3 or later (GPLv3+)"
author = 'Nicolas OGIER'
author_email = "info@nicolas-ogier.fr"

[tool.briefcase.app.automultiplechoicegenerator]
formal_name = "Générateur de QCM pour AMC"
description = "Générateur de questionnaire à choix multiples pour le logiciel Auto-Multiple-Choice."
icon = "src/automultiplechoicegenerator/resources/automultiplechoicegenerator"
sources = ['src/automultiplechoicegenerator']
requires = []


[tool.briefcase.app.automultiplechoicegenerator.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.automultiplechoicegenerator.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.automultiplechoicegenerator.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.automultiplechoicegenerator.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.automultiplechoicegenerator.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
